apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: optaplannerworkshops.workshop.optaplanner.org
spec:
  group: workshop.optaplanner.org
  names:
    kind: OptaPlannerWorkshop
    listKind: OptaPlannerWorkshopList
    plural: optaplannerworkshops
    singular: optaplannerworkshop
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
